import Head from 'next/head'

import styles from '<cines-sj>/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { Layout } from '<cines-sj>/components/layout'


export default function Home({ movieData, error }: { movieData: any, error: any }) {
  const [movies, setMovies] = useState<any[]>([]);

  useEffect(() => {
    if (movieData) {
      setMovies(movieData['movies'])
    }
    else if (error) {
      console.log(error)
    }
  }, []);

  return (
    <>
      <Head>
        <title>Cinema SJ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <div className={styles.mainLayout}> */}
        <div className={styles.mainGrid}>
          {movies.map(item => (
            <div className={styles.gridItem} key={item.movie_id}>
              <Link href={`/movies/${encodeURIComponent(item.movie_id)}`}>
                {/* <div style={{ width: '100%', height: '100%', position: 'relative' }}> */}
                <Image
                  className={styles.image}
                  src={item.image_url}
                  alt="movie poster"
                  fill={true}
                />
                {/* </div> */}
              </Link>
            </div>
          ))}
          {/* </div> */}
        </div>
      </Layout>
    </>
  )
}

export async function getStaticProps() {

  try {
    let movieData = await fetch(`http://localhost:8010/movies/`)
      .then((response) => response.json())


    return {
      props: { movieData: movieData }, // will be passed to the page component as props
    }
  } catch (error) {
    console.log('There was an error', error);
    return {
      props: {
        error: "API error, connection failed"
      }
    }
  }
}
